# Generated by Django 5.2.6 on 2025-09-20 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_bookmark', to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blog_bookmark',
                'indexes': [models.Index(fields=['user'], name='blog_bookma_user_id_7460b9_idx'), models.Index(fields=['post'], name='blog_bookma_post_id_410976_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_bookmark')],
            },
        ),
    ]
